use ../src/cs2cs for testing by default
git-svn-id: http://svn.osgeo.org/metacrs/proj/trunk@1884 4e78687f-474d-0410-85f9-8d5e500ac6b2

diff --git a/nad/test83 b/nad/test83
--- a/nad/test83
+++ b/nad/test83
@@ -17,13 +17,12 @@ usage()
 }
 
 if test -z "${EXE}"; then
-    echo "*** ERROR: Missing path to 'proj' program."
-    usage
-else
-    if test ! -x ${EXE}; then
-        echo "*** ERROR: Can not find '${EXE}' program!"
-        exit 1
-    fi
+    EXE=../src/cs2cs
+fi
+
+if test ! -x ${EXE}; then
+    echo "*** ERROR: Can not find '${EXE}' program!"
+    exit 1
 fi
 
 echo "============================================"
