Added 'make check' target to run tests.
git-svn-id: http://svn.osgeo.org/metacrs/proj/trunk@1355 4e78687f-474d-0410-85f9-8d5e500ac6b2

diff --git a/nad/test83 b/nad/test83
--- a/nad/test83
+++ b/nad/test83
@@ -7,8 +7,30 @@
 # Proj will vary in the .001ft range with projections using Transverse
 #   Mercator due to greater precision of meridinal distance function.
 #
+EXE=$1
+
+usage()
+{
+    echo "Usage: ${0} <path to 'proj' program>" 
+    echo
+    exit 1
+}
+
+if test -z "${EXE}"; then
+    echo "*** ERROR: Missing path to 'proj' program."
+    usage
+else
+    if test ! -x ${EXE}; then
+        echo "*** ERROR: Can not find '${EXE}' program!"
+        exit 1
+    fi
+fi
+
+echo "============================================"
+echo "Running ${0} using ${EXE}:"
+echo "============================================"
+
 OUT=proj_out83
-EXE=../src/proj
 INIT_FILE=./nad83
 #
 echo "doing tests into file ${OUT}, please wait"
@@ -696,10 +718,12 @@ if [ $? -ne 0 ] ; then
 	echo  ""
 	echo "PROBLEMS HAVE OCCURED"
 	echo "test file ${OUT} saved"
+    echo
 	exit 100
 else
 	echo "TEST OK"
 	echo "test file ${OUT} removed"
+    echo
 	/bin/rm -f ${OUT}
 	exit 0
 fi
diff --git a/nad/testntv2 b/nad/testntv2
--- a/nad/testntv2
+++ b/nad/testntv2
@@ -3,8 +3,31 @@
 # Test NTv2 (.gsb) support.  Assumes ntv2_0.gsb is installed.
 #
 #
+EXE=$1
+
+usage()
+{
+    echo "Usage: ${0} <path to 'cs2cs' program>" 
+    echo
+    exit 1
+}
+
+if test -z "${EXE}"; then
+    echo "*** ERROR: Missing path to 'cs2cs' program."
+    usage
+else
+    if test ! -x ${EXE}; then
+        echo "*** ERROR: Can not find '${EXE}' program!"
+        exit 1
+    fi
+fi
+
+echo "============================================"
+echo "Running ${0} using ${EXE}:"
+echo "============================================"
+
 OUT=ntv2_out
-EXE=../src/cs2cs
+#EXE=../src/cs2cs
 #
 echo "doing tests into file ${OUT}, please wait"
 rm -f ${OUT}
@@ -39,8 +62,13 @@ if [ $? -ne 0 ] ; then
 	echo  ""
 	echo "PROBLEMS HAVE OCCURED"
 	echo "test file ${OUT} saved"
+    echo
+    exit 100
 else
 	echo "TEST OK"
 	echo "test file ${OUT} removed"
+    echo
 	/bin/rm -f ${OUT}
+    exit 0
 fi
+
diff --git a/nad/testvarious b/nad/testvarious
--- a/nad/testvarious
+++ b/nad/testvarious
@@ -2,8 +2,31 @@
 # Script to do some testing of various transformation.
 #
 #
+EXE=$1
+
+usage()
+{
+    echo "Usage: ${0} <path to 'cs2cs' program>" 
+    echo
+    exit 1
+}
+
+if test -z "${EXE}"; then
+    echo "*** ERROR: Missing path to 'cs2cs' program."
+    usage
+else
+    if test ! -x ${EXE}; then
+        echo "*** ERROR: Can not find '${EXE}' program!"
+        exit 1
+    fi
+fi
+
+echo "============================================"
+echo "Running ${0} using ${EXE}:"
+echo "============================================"
+
 OUT=td_out
-EXE=../src/cs2cs
+#EXE=../src/cs2cs
 #
 echo "doing tests into file ${OUT}, please wait"
 rm -f ${OUT}
@@ -150,10 +173,12 @@ if [ $? -ne 0 ] ; then
 	echo  ""
 	echo "PROBLEMS HAVE OCCURED"
 	echo "test file ${OUT} saved"
+    echo
 	exit 100
 else
 	echo "TEST OK"
 	echo "test file ${OUT} removed"
+    echo
 	/bin/rm -f ${OUT}
 	exit 0
 fi
