Implement RFC 2: Initial integration of "GDAL SRS barn" work
This work mostly consists of:
- a C++ implementation of the ISO-19111:2018 / OGC Topic 2
  "Referencing by coordinates" classes to represent Datums,
  Coordinate systems, CRSs (Coordinate Reference Systems) and
  Coordinate Operations.
- methods to convert between this C++ modeling and WKT1, WKT2
  and PROJ string representations of those objects
- management and query of a SQLite3 database of CRS and Coordinate Operation definition
- a C API binding part of those capabilities

This is all-in-one squashed commit of the work of
https://github.com/OSGeo/proj.4/pull/1040

diff --git a/data/Makefile.am b/data/Makefile.am
--- a/data/Makefile.am
+++ b/data/Makefile.am
@@ -3,14 +3,45 @@ DATAPATH = $(top_srcdir)/data
 pkgdata_DATA = GL27 nad.lst proj_def.dat nad27 nad83 world epsg esri \
 		esri.extra other.extra \
 		CH IGNF \
-		ITRF2000 ITRF2008 ITRF2014
+		ITRF2000 ITRF2008 ITRF2014 proj.db
+
+SQL_ORDERED_LIST = sql/begin.sql \
+		sql/proj_db_table_defs.sql \
+		sql/conversion_triggers.sql \
+		sql/metadata.sql \
+		sql/unit_of_measure.sql \
+		sql/area.sql \
+		sql/coordinate_system.sql \
+		sql/axis.sql \
+		sql/ellipsoid.sql \
+		sql/prime_meridian.sql \
+		sql/geodetic_datum.sql \
+		sql/vertical_datum.sql \
+		sql/conversion.sql \
+		sql/geodetic_crs.sql \
+		sql/projected_crs.sql \
+		sql/vertical_crs.sql \
+		sql/compound_crs.sql \
+		sql/helmert_transformation.sql \
+		sql/grid_transformation.sql \
+		sql/grid_transformation_custom.sql \
+		sql/other_transformation.sql \
+		sql/concatenated_operation.sql \
+		sql/esri.sql \
+		sql/ignf.sql \
+		sql/grid_alternatives.sql \
+		sql/grid_alternatives_generated.sql \
+		sql/customizations.sql \
+		sql/commit.sql
 
 EXTRA_DIST = GL27 nad.lst proj_def.dat nad27 nad83 \
 		world epsg esri \
 		esri.extra other.extra \
 		CH IGNF \
 		ITRF2000 ITRF2008 ITRF2014 \
-		CMakeLists.txt tests/test_nodata.gtx null.lla
+		CMakeLists.txt tests/test_nodata.gtx null.lla \
+		generate_all_sql_in.cmake sql_filelist.cmake \
+		$(SQL_ORDERED_LIST)
 
 process-nad2bin:
 	@if [ -f $(DATAPATH)/null.lla -a ! -f null ] || [ -f $(DATAPATH)/conus.lla -a ! -f conus ] ; then \
@@ -46,6 +77,26 @@ install-data-local: process-nad2bin
           fi; \
 	done
 
+proj.db: $(DATAPATH)/sql/*.sql
+	@echo "Make proj.db"
+	$(RM) proj.db
+	@export SQL_EXPANDED_LIST=""; \
+	 for x in $(SQL_ORDERED_LIST); do \
+		export SQL_EXPANDED_LIST="$${SQL_EXPANDED_LIST} $(DATAPATH)/$$x"; \
+	 done; \
+	 cat $${SQL_EXPANDED_LIST} | sqlite3 proj.db; \
+	 if [ $$? -ne 0 ] ; then \
+		echo "Build of proj.db failed"; \
+		$(RM) proj.db; \
+		exit 1; \
+	fi; \
+	 if [[ $$(echo "pragma foreign_key_check;" | sqlite3 proj.db | head -c1 | wc -c) -ne 0 ]]; then \
+		echo "Foreign key check failed"; \
+		$(RM) proj.db; \
+		exit 1; \
+	 fi
+
+	
 # For out-of-tree builds, link all file of the source data dir to the generated data
 check-local: process-nad2bin
 	@if [ ! -f GL27 ]; then \
