Make tests independent of proj-datumgrid
Fixes #1984

- Copy BETA2007.gsb, MD, alaska, conus, ntf_r93.gsb, ntv1_can.dat grids
  from proj-datumgrid to data/tests.
- Replace a couple uses of nzgd2kgrid0005.gsb in tests by ntf_r93.gsb
- Add downsampled/subsetted versions of egm96_15.gtx as tests/egm96_15_downsampled.gtx
  and ntv2_0.gsb as tests/ntv2_0_downsampled.gsb
  This results in a few changes in expected results
- Simpify travis/install.sh due to less configurations to test

This results in a hopefully acceptable increase of the proj-X.Y.Z.tar.gz
from 2.9 to 5.3 MB

diff --git a/data/Makefile.am b/data/Makefile.am
--- a/data/Makefile.am
+++ b/data/Makefile.am
@@ -89,6 +89,14 @@ EXTRA_DIST = proj.ini GL27 nad.lst nad27 nad83 \
 		tests/us_noaa_geoid06_ak_subset_at_antimeridian.tif \
 		tests/test_hgrid_little_endian.gsb \
 		tests/test_hgrid_big_endian.gsb \
+		tests/BETA2007.gsb \
+		tests/MD \
+		tests/alaska \
+		tests/conus \
+		tests/egm96_15_downsampled.gtx \
+		tests/ntv1_can.dat \
+		tests/ntv2_0_downsampled.gsb \
+		tests/ntf_r93.gsb \
 		generate_all_sql_in.cmake sql_filelist.cmake \
 		$(SQL_ORDERED_LIST)
 
@@ -143,6 +151,19 @@ proj.db: $(DATAPATH)/sql/*.sql
 # For out-of-tree builds, link all file of the source data dir to the generated data
 # Also link select resource files in a for_tests subdirectory so that we are not
 # influenced by the presence of other grids
+
+# egm96_15_downsampled.gtx created with
+# gdal_translate proj-datumgrid/egm96_15.gtx egm96_15_downsampled.gtx -of GTX -outsize 25% 25% -r average
+
+# ntv2_0_downsampled.gsb created with:
+# gdal_translate NTv2:0:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -outsize 10% 10%
+# gdal_translate NTv2:1:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -outsize 10% 10% -co append_subdataset=yes
+# gdal_translate NTv2:2:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -outsize 10% 10% -co append_subdataset=yes
+# gdal_translate NTv2:3:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -outsize 10% 10% -co append_subdataset=yes
+# gdal_translate NTv2:99:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -co append_subdataset=yes
+# gdal_translate NTv2:44:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -co append_subdataset=yes
+# gdal_translate NTv2:4:/home/even/proj/proj-datumgrid/north-america/ntv2_0.gsb  /tmp/ntv2_0_downsampled.gsb -of NTv2 -co append_subdataset=yes
+
 check-local:
 	@if [ ! -f GL27 ]; then \
 		for x in $(DATAPATH)/*; do \
@@ -154,24 +175,24 @@ check-local:
 	for x in $(DATAPATH)/GL27 \
 		 $(DATAPATH)/nad27 \
 		 $(DATAPATH)/nad83 \
-		 $(DATAPATH)/ntv1_can.dat \
-		 $(DATAPATH)/MD \
-		 $(DATAPATH)/ntf_r93.gsb \
-		 $(DATAPATH)/egm96_15.gtx \
-		 $(DATAPATH)/ntv2_0.gsb \
-		 $(DATAPATH)/conus \
-		 $(DATAPATH)/alaska \
-		 $(DATAPATH)/nzgd2kgrid0005.gsb \
+		 $(DATAPATH)/tests/ntv1_can.dat \
+		 $(DATAPATH)/tests/MD \
+		 $(DATAPATH)/tests/ntf_r93.gsb \
+		 $(DATAPATH)/tests/conus \
+		 $(DATAPATH)/tests/alaska \
 		 $(DATAPATH)/ITRF2000 \
-		 $(DATAPATH)/BETA2007.gsb; \
+		 $(DATAPATH)/tests/BETA2007.gsb; \
 	do \
 		if test -f "$$x" ; then \
 			ln -sf "../$$x" for_tests; \
 		else \
-			echo "WARNING: grid $$x missing: some tests will be skipped"; \
+			echo "ERROR: grid $$x missing: some tests will be skipped"; \
+			exit 1; \
 		fi \
 	done; \
 	ln -sf ../$(DATAPATH)/tests for_tests; \
+	ln -sf ../$(DATAPATH)/tests/ntv2_0_downsampled.gsb for_tests/ntv2_0.gsb; \
+	ln -sf ../$(DATAPATH)/tests/egm96_15_downsampled.gtx for_tests/egm96_15.gtx; \
 	ln -sf ../$(DATAPATH)/proj.ini for_tests; \
 	ln -sf ../proj.db for_tests
 
